version: '3.1'

services:
  # Cypress container
  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: "cypress/included:3.2.0"
    depends_on:
      - ghost
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://ghost:2368/ghost
    # share the current folder as volume to avoid copying
    working_dir: /e2e
    volumes:
      - ./:/e2e    
  ghost:
    image: ghost:5.96.0
    restart: always
    ports:
      - 8080:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      url: http://localhost:8080
      NODE_ENV: development
    volumes:
      - ghost:/var/lib/ghost/content

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db:/var/lib/mysql

volumes:
  ghost:
  db:
